# Generated by Django 5.2.9 on 2026-01-22 22:22

import cms_mcp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique prompt name (identifier used by clients).",
                        max_length=200,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the prompt.",
                        verbose_name="description",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The prompt content, preferably in Markdown format.",
                        verbose_name="content",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If disabled, the prompt will not be listed by MCP.",
                        verbose_name="enabled",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MCP prompt",
                "verbose_name_plural": "MCP prompts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MCPResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        help_text="Unique resource URI (e.g., cms://pages or cms://pages/123).",
                        max_length=255,
                        unique=True,
                        validators=[cms_mcp.models.MCPResource.validate_resource_uri],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the resource.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the resource."
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        choices=[
                            ("text/markdown", "text/markdown (Markdown)"),
                            ("text/plain", "text/plain (Plain text)"),
                            ("text/html", "text/html (HTML)"),
                            ("text/csv", "text/csv (CSV)"),
                            ("application/json", "JSON"),
                            ("application/schema+json", "JSON Schema"),
                            ("application/yaml", "YAML"),
                            ("application/toml", "TOML"),
                            ("application/xml", "XML"),
                        ],
                        default="text/markdown",
                        help_text="MIME type of the resource content.",
                        max_length=100,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If disabled, the resource will not be listed by MCP.",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Arbitrary JSON content returned by the MCP resource.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MCP resource",
                "verbose_name_plural": "MCP resources",
                "ordering": ["uri"],
            },
        ),
        migrations.CreateModel(
            name="MCPToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=cms_mcp.models.generate_token,
                        help_text="Automatically generated secure token. Used for API authentication.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, this token cannot be used for authentication.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        default=cms_mcp.models.get_default_expiry,
                        help_text="When the token expires and becomes invalid. Leave empty for no expiration.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MCP token",
                "verbose_name_plural": "MCP tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
